apiVersion: v1
kind: Namespace
metadata:
  name: student-apps
---  
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-website-config
  namespace: student-apps
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>GitOps Demo</title></head>
    <body style="background-color: #2d3436; color: black; text-align: center; padding-top: 50px;">
      <h1>Hello Class 1125!</h1>
      <p>Deployed via ArgoCD</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-deployment
  namespace: student-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-site
  template:
    metadata:
      labels:
        app: nginx-site
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: web-content
          configMap:
            name: my-website-config
            items:
              - key: index.html
                path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: argo-network
  namespace: student-apps
spec:
  type: LoadBalancer
  selector:
    app: nginx-site
  ports:
    - name: http
      port: 80
      targetPort: 80
